# Generated by Django 2.0.7 on 2018-07-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year')),
                ('released', models.DateField(blank=True, max_length=255, null=True, verbose_name='Released')),
                ('runtime', models.CharField(blank=True, max_length=255, null=True, verbose_name='Runtime')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Genre')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='Director')),
                ('writer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Writer')),
                ('actors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Actors')),
                ('plot', models.TextField(blank=True, null=True, verbose_name='Plot')),
                ('language', models.CharField(blank=True, max_length=255, null=True, verbose_name='Language')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_movie_db.Movie'),
        ),
    ]
